version: '3.9'

networks:
  observability_poc:
    external: true
    name: observability_poc

volumes:
  observability_poc:
    external: true
    name: observability_poc

services:
  collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel-collector/config.yml" ]
    ports:
      - "8889:8889"
      - "55679:55679"
    volumes:
      - ./otel-collector:/etc/otel-collector/
    depends_on:
      - tempo
    networks:
      - observability_poc

  grafana:
    image: grafana/grafana-oss:9.3.2
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
    networks:
      - observability_poc
    ports:
      - "3000:3000"

  tempo:
    image: grafana/tempo:1.5.0
    command: --config.file=/etc/tempo/config.yml
    volumes:
      - ./tempo:/etc/tempo:ro
    networks:
      - observability_poc
